### ISSUE TITLE
Error generating errors

### ISSUE THREAD

**Issue by matthewroach** [OpenBD/openbd-core#5]
I am seeing the following stack trace in the jetty desktop console when a runtime or internal server error happens

My bluedragon temp-directory setting is

```
<tempdirectory>$/tmp/dev/</tempdirectory>
```

Error:

```
... Jetty has started.
2015-05-20 22:06:33.393:WARN:oejur.FileResource:EXCEPTION 
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
    at java.io.WinNTFileSystem.canonicalize0(Native Method)
    at java.io.WinNTFileSystem.canonicalize(Unknown Source)
    at java.io.File.getCanonicalPath(Unknown Source)
    at org.eclipse.jetty.util.resource.FileResource.getAlias(FileResource.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.getResource(ContextHandler.java:1526)
    at org.eclipse.jetty.webapp.WebAppContext.getResource(WebAppContext.java:320)
    at org.eclipse.jetty.server.handler.ContextHandler$Context.getRealPath(ContextHandler.java:1827)
    at org.eclipse.jetty.server.Request.getRealPath(Request.java:837)
    at com.nary.io.FileUtils.getRealPath(Unknown Source)
    at com.naryx.tagfusion.cfm.file.cfmlURI.getRealPath(Unknown Source)
    at com.naryx.tagfusion.cfm.file.cfmlFileCache.loadFile(Unknown Source)
    at com.naryx.tagfusion.cfm.file.cfmlFileCache._getCfmlFile(Unknown Source)
    at com.naryx.tagfusion.cfm.file.cfmlFileCache.getCfmlFile(Unknown Source)
    at com.naryx.tagfusion.cfm.engine.cfSession.getFile(Unknown Source)
    at com.naryx.tagfusion.cfm.engine.cfmRunTimeException.runDefaultErrorHandler(Unknown Source)
    at com.naryx.tagfusion.cfm.engine.cfmRunTimeException.handleException(Unknown Source)
    at com.naryx.tagfusion.cfm.engine.cfEngine.service(Unknown Source)
    at com.naryx.tagfusion.cfm.cfServlet.service(Unknown Source)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:575)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:485)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:537)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:233)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:412)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:271)
    at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:98)
    at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:557)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:575)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1365)
    at com.newatlanta.filters.SearchEngineFriendlyURLFilter.doFilter(Unknown Source)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1336)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:483)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:519)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:233)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:412)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
    at org.eclipse.jetty.server.Server.handle(Server.java:351)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:451)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:916)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:634)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:611)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
    at java.lang.Thread.run(Unknown Source)
2015-05-20 22:06:33.393:WARN:oejur.FileResource:EXCEPTION 
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
    at java.io.WinNTFileSystem.canonicalize0(Native Method)
    at java.io.WinNTFileSystem.canonicalize(Unknown Source)
    at java.io.File.getCanonicalPath(Unknown Source)
    at org.eclipse.jetty.util.resource.FileResource.getAlias(FileResource.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.getResource(ContextHandler.java:1526)
    at org.eclipse.jetty.webapp.WebAppContext.getResource(WebAppContext.java:320)
    at org.eclipse.jetty.webapp.WebAppContext$Context.getResource(WebAppContext.java:1222)
    at com.nary.io.FileUtils.getWebLogicRealPath(Unknown Source)
    at com.nary.io.FileUtils.getRealPath(Unknown Source)
    at com.naryx.tagfusion.cfm.file.cfmlURI.getRealPath(Unknown Source)
    at com.naryx.tagfusion.cfm.file.cfmlFileCache.loadFile(Unknown Source)
    at com.naryx.tagfusion.cfm.file.cfmlFileCache._getCfmlFile(Unknown Source)
    at com.naryx.tagfusion.cfm.file.cfmlFileCache.getCfmlFile(Unknown Source)
    at com.naryx.tagfusion.cfm.engine.cfSession.getFile(Unknown Source)
    at com.naryx.tagfusion.cfm.engine.cfmRunTimeException.runDefaultErrorHandler(Unknown Source)
    at com.naryx.tagfusion.cfm.engine.cfmRunTimeException.handleException(Unknown Source)
    at com.naryx.tagfusion.cfm.engine.cfEngine.service(Unknown Source)
    at com.naryx.tagfusion.cfm.cfServlet.service(Unknown Source)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:575)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:485)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:537)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:233)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:412)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:271)
    at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:98)
    at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:557)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:575)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1365)
    at com.newatlanta.filters.SearchEngineFriendlyURLFilter.doFilter(Unknown Source)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1336)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:483)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:519)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:233)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:412)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
    at org.eclipse.jetty.server.Server.handle(Server.java:351)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:451)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:916)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:634)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:611)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
    at java.lang.Thread.run(Unknown Source)
2015-05-20 22:06:33.409:WARN:oejur.FileResource:EXCEPTION 
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
    at java.io.WinNTFileSystem.canonicalize0(Native Method)
    at java.io.WinNTFileSystem.canonicalize(Unknown Source)
    at java.io.File.getCanonicalPath(Unknown Source)
    at org.eclipse.jetty.util.resource.FileResource.getAlias(FileResource.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.getResource(ContextHandler.java:1526)
    at org.eclipse.jetty.webapp.WebAppContext.getResource(WebAppContext.java:320)
    at org.eclipse.jetty.server.handler.ContextHandler$Context.getRealPath(ContextHandler.java:1827)
    at com.nary.io.FileUtils.getRealPath(Unknown Source)
    at com.naryx.tagfusion.cfm.file.cfmlURI.getRealPath(Unknown Source)
    at com.naryx.tagfusion.cfm.file.cfmlFileCache.loadFile(Unknown Source)
    at com.naryx.tagfusion.cfm.file.cfmlFileCache._getCfmlFile(Unknown Source)
    at com.naryx.tagfusion.cfm.file.cfmlFileCache.getCfmlFile(Unknown Source)
    at com.naryx.tagfusion.cfm.engine.cfSession.getFile(Unknown Source)
    at com.naryx.tagfusion.cfm.engine.cfmRunTimeException.runDefaultErrorHandler(Unknown Source)
    at com.naryx.tagfusion.cfm.engine.cfmRunTimeException.handleException(Unknown Source)
    at com.naryx.tagfusion.cfm.engine.cfEngine.service(Unknown Source)
    at com.naryx.tagfusion.cfm.cfServlet.service(Unknown Source)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:575)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:485)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:537)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:233)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:412)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:271)
    at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:98)
    at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:557)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:575)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1365)
    at com.newatlanta.filters.SearchEngineFriendlyURLFilter.doFilter(Unknown Source)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1336)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:483)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:519)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:233)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:412)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
    at org.eclipse.jetty.server.Server.handle(Server.java:351)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:451)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:916)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:634)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:611)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
    at java.lang.Thread.run(Unknown Source)
```

**Comment by wua22** [comment]
What's the path to your default error handler defined as in the 
bluedragon.xml? Does the file exist?

**Comment by matthewroach** [comment]
Looks like the error handler in bluedragon.xml is causing this. I have it set to

`<errorhandler>/error.cfm?s=500</errorhandler>`

but if I change it to

`<errorhandler>error.cfm?s=500</errorhandler>`

errors disappear

**Comment by a1anw2** [comment]
Good news i have recreated it ... though i think @matthewroach report is a little wrong (typing error?).

These combinations work with no problems:

```
<errorhandler>/error.cfm</errorhandler>
<errorhandler>error.cfm</errorhandler>
```

this however, causes an error; it is treating the whole string as a file path.  This is not a URL you are passing in, but the path to the file name.

```
<errorhandler>error.cfm?s=500</errorhandler>
```

Remove the ?s=500 and all is well.  This isn't a bug; the feature you think you are wanting isn't supported.
